layout_spectrum: 0.4731183
typography_spectrum: 0.7706093
color:
  saturation: 0.07373109
  lightness: 0.7702277
  brandStrength: 0.4330575
  rhythmicContrast: 0.5685843
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Jeffereyrondeau
